# Generated by Django 5.1.5 on 2025-03-11 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Produtos',
        ),
        migrations.RenameModel(
            old_name='Order',
            new_name='Vendas',
        ),
        migrations.RenameModel(
            old_name='Seller',
            new_name='Vendedor',
        ),
    ]
