# Generated by Django 5.1.5 on 2025-03-12 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_product_produtos_rename_order_vendas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendas',
            old_name='date',
            new_name='data',
        ),
    ]
