# Generated by Django 5.1.5 on 2025-03-08 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyAccess',
        ),
    ]
